namespace xAPI.Client.Exceptions
{
    /// <summary>
    /// The common class for HTTP exceptions generated by the xAPI client.
    /// Any derived type corresponds to a specific HTTP status code.
    /// </summary>
    public abstract class HttpException : XApiException
    {
        /// <summary>
        /// Creates a new instance of HttpException.
        /// </summary>
        /// <param name="message">The exception's message.</param>
        public HttpException(string message) : base(message)
        {
        }
    }
}
